### ISSUE TITLE
Prices not updating

### ISSUE THREAD

**Issue by SheeranJL** [mihailgaberov/orderbook#1]
The prices don't seem to update on the demo - just curious if this a known issue?

https://orderbook-mihailgaberov.vercel.app/

**Comment by mihailgaberov** [comment]
Hey, thanks for letting me know!

Not sure if this is an issue in the app as I haven't changed anything recently. It might be worth to check the source at wss://www.cryptofacilities.com/ws/v1 and see what coming from there.
