### ISSUE TITLE
Grouping is not working properly

### ISSUE THREAD

**Issue by sawrubgupta** [mihailgaberov/orderbook#2]
Hello, really thank you for this repository and tutorial, but can you please fix the grouping this, if we select 2.5 as grouping mulitple duplicate price row shows in order book

like 

40302.5       0.06
40302.5       0
40302.5       0

**Comment by mihailgaberov** [comment]
Hey, thank you for reporting that. Unfortunately I am short on time lately and I do not know when I will have the chance to take a look at this. But if you decide to give a try, any PRs are welcome.
